/*
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ycloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Indicates who initiated the conversation. **Note: Starting June 1, 2023, &#x60;business_initiated&#x60; will be replaced with &#x60;authentication&#x60;, &#x60;marketing&#x60;, and &#x60;utility&#x60;, while &#x60;user_initiated&#x60; will be replaced with &#x60;service&#x60;. For more information, see also [Updates to conversation-based pricing: Effective June 1, 2023](https://developers.facebook.com/docs/whatsapp/updates-to-pricing).**  - &#x60;business_initiated&#x60;: Indicates that the conversation started by a business sending the first message to a customer. This applies any time it has been more than 24 hours since the last customer message. - &#x60;user_initiated&#x60;: Indicates that the conversation started by a business replying to a customer message. This applies only when the business reply is within 24 hours of the last customer message. - &#x60;referral_conversion&#x60;: Indicates the user initiated the conversation by clicking a [Click to WhatsApp ad](https://www.facebook.com/business/help/447934475640650) or a [Facebook Page Call-to-Action button](https://www.facebook.com/help/977869848936797). - &#x60;authentication&#x60;: Indicates the business initiated the conversation with a message template categorized as &#x60;AUTHENTICATION&#x60;. - &#x60;marketing&#x60;: Indicates the business initiated the conversation with a message template categorized as &#x60;MARKETING&#x60;. - &#x60;utility&#x60;: Indicates the business initiated the conversation with a message template categorized as &#x60;UTILITY&#x60;. - &#x60;service&#x60;: Indicates the user initiated the conversation.
 */
@JsonAdapter(WhatsappConversationOriginType.Adapter.class)
public enum WhatsappConversationOriginType {
  
  BUSINESS_INITIATED("business_initiated"),
  
  USER_INITIATED("user_initiated"),
  
  REFERRAL_CONVERSION("referral_conversion"),
  
  AUTHENTICATION("authentication"),
  
  MARKETING("marketing"),
  
  UTILITY("utility"),
  
  SERVICE("service");

  private String value;

  WhatsappConversationOriginType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WhatsappConversationOriginType fromValue(String value) {
    for (WhatsappConversationOriginType b : WhatsappConversationOriginType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WhatsappConversationOriginType> {
    @Override
    public void write(final JsonWriter jsonWriter, final WhatsappConversationOriginType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WhatsappConversationOriginType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WhatsappConversationOriginType.fromValue(value);
    }
  }
}

