/*
 * YCloud API
 * The [YCloud](https://ycloud.com) API is organized around [REST](https://en.wikipedia.org/wiki/Representational_state_transfer). Our API is designed to have predictable, resource-oriented URLs, return [JSON](https://www.json.org) responses, and use standard HTTP response codes and verbs.
 *
 * The version of the OpenAPI document: v2
 * Contact: service@ycloud.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ycloud.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets WhatsappTemplateComponentButtonType
 */
@JsonAdapter(WhatsappTemplateComponentButtonType.Adapter.class)
public enum WhatsappTemplateComponentButtonType {
  
  PHONE_NUMBER("PHONE_NUMBER"),
  
  URL("URL"),
  
  QUICK_REPLY("QUICK_REPLY");

  private String value;

  WhatsappTemplateComponentButtonType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static WhatsappTemplateComponentButtonType fromValue(String value) {
    for (WhatsappTemplateComponentButtonType b : WhatsappTemplateComponentButtonType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<WhatsappTemplateComponentButtonType> {
    @Override
    public void write(final JsonWriter jsonWriter, final WhatsappTemplateComponentButtonType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public WhatsappTemplateComponentButtonType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return WhatsappTemplateComponentButtonType.fromValue(value);
    }
  }
}

